// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEntity_Dapper.Models;

#nullable disable

namespace ProjectEntity_Dapper.Migrations
{
    [DbContext(typeof(WarehouseDBContext))]
    partial class WarehouseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home Appliances"
                        });
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "New York",
                            Country = "USA",
                            CustomerName = "John Doe",
                            Email = "johndoe@example.com",
                            Notes = "Regular customer",
                            PhoneNumber = "1234567890",
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            City = "Los Angeles",
                            Country = "USA",
                            CustomerName = "Jane Smith",
                            Email = "janesmith@example.com",
                            Notes = "VIP customer",
                            PhoneNumber = "0987654321",
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "15 Nile St",
                            City = "Cairo",
                            Country = "Egypt",
                            CustomerName = "Ali Hassan",
                            Email = "alihassan@example.com",
                            Notes = "Inactive account",
                            PhoneNumber = "01011223344",
                            isActive = false
                        });
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceDetailId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceDetailId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Invoicess", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("catid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("catid");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "P001",
                            Name = "Product 1",
                            Note = "Description for product 1",
                            Price = 15.0m,
                            Quantity = 99,
                            catid = 2
                        },
                        new
                        {
                            Id = 2,
                            Code = "P002",
                            Name = "Product 2",
                            Note = "Description for product 2",
                            Price = 20.0m,
                            Quantity = 98,
                            catid = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "P003",
                            Name = "Product 3",
                            Note = "Description for product 3",
                            Price = 25.0m,
                            Quantity = 97,
                            catid = 4
                        },
                        new
                        {
                            Id = 4,
                            Code = "P004",
                            Name = "Product 4",
                            Note = "Description for product 4",
                            Price = 30.0m,
                            Quantity = 96,
                            catid = 5
                        },
                        new
                        {
                            Id = 5,
                            Code = "P005",
                            Name = "Product 5",
                            Note = "Description for product 5",
                            Price = 35.0m,
                            Quantity = 95,
                            catid = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "P006",
                            Name = "Product 6",
                            Note = "Description for product 6",
                            Price = 40.0m,
                            Quantity = 94,
                            catid = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = "P007",
                            Name = "Product 7",
                            Note = "Description for product 7",
                            Price = 45.0m,
                            Quantity = 93,
                            catid = 3
                        },
                        new
                        {
                            Id = 8,
                            Code = "P008",
                            Name = "Product 8",
                            Note = "Description for product 8",
                            Price = 50.0m,
                            Quantity = 92,
                            catid = 4
                        },
                        new
                        {
                            Id = 9,
                            Code = "P009",
                            Name = "Product 9",
                            Note = "Description for product 9",
                            Price = 55.0m,
                            Quantity = 91,
                            catid = 5
                        },
                        new
                        {
                            Id = 10,
                            Code = "P010",
                            Name = "Product 10",
                            Note = "Description for product 10",
                            Price = 60.0m,
                            Quantity = 90,
                            catid = 1
                        },
                        new
                        {
                            Id = 11,
                            Code = "P011",
                            Name = "Product 11",
                            Note = "Description for product 11",
                            Price = 65.0m,
                            Quantity = 89,
                            catid = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "P012",
                            Name = "Product 12",
                            Note = "Description for product 12",
                            Price = 70.0m,
                            Quantity = 88,
                            catid = 3
                        },
                        new
                        {
                            Id = 13,
                            Code = "P013",
                            Name = "Product 13",
                            Note = "Description for product 13",
                            Price = 75.0m,
                            Quantity = 87,
                            catid = 4
                        },
                        new
                        {
                            Id = 14,
                            Code = "P014",
                            Name = "Product 14",
                            Note = "Description for product 14",
                            Price = 80.0m,
                            Quantity = 86,
                            catid = 5
                        },
                        new
                        {
                            Id = 15,
                            Code = "P015",
                            Name = "Product 15",
                            Note = "Description for product 15",
                            Price = 85.0m,
                            Quantity = 85,
                            catid = 1
                        },
                        new
                        {
                            Id = 16,
                            Code = "P016",
                            Name = "Product 16",
                            Note = "Description for product 16",
                            Price = 90.0m,
                            Quantity = 84,
                            catid = 2
                        },
                        new
                        {
                            Id = 17,
                            Code = "P017",
                            Name = "Product 17",
                            Note = "Description for product 17",
                            Price = 95.0m,
                            Quantity = 83,
                            catid = 3
                        },
                        new
                        {
                            Id = 18,
                            Code = "P018",
                            Name = "Product 18",
                            Note = "Description for product 18",
                            Price = 100.0m,
                            Quantity = 82,
                            catid = 4
                        },
                        new
                        {
                            Id = 19,
                            Code = "P019",
                            Name = "Product 19",
                            Note = "Description for product 19",
                            Price = 105.0m,
                            Quantity = 81,
                            catid = 5
                        },
                        new
                        {
                            Id = 20,
                            Code = "P020",
                            Name = "Product 20",
                            Note = "Description for product 20",
                            Price = 110.0m,
                            Quantity = 80,
                            catid = 1
                        },
                        new
                        {
                            Id = 21,
                            Code = "P021",
                            Name = "Product 21",
                            Note = "Description for product 21",
                            Price = 115.0m,
                            Quantity = 79,
                            catid = 2
                        },
                        new
                        {
                            Id = 22,
                            Code = "P022",
                            Name = "Product 22",
                            Note = "Description for product 22",
                            Price = 120.0m,
                            Quantity = 78,
                            catid = 3
                        },
                        new
                        {
                            Id = 23,
                            Code = "P023",
                            Name = "Product 23",
                            Note = "Description for product 23",
                            Price = 125.0m,
                            Quantity = 77,
                            catid = 4
                        },
                        new
                        {
                            Id = 24,
                            Code = "P024",
                            Name = "Product 24",
                            Note = "Description for product 24",
                            Price = 130.0m,
                            Quantity = 76,
                            catid = 5
                        },
                        new
                        {
                            Id = 25,
                            Code = "P025",
                            Name = "Product 25",
                            Note = "Description for product 25",
                            Price = 135.0m,
                            Quantity = 75,
                            catid = 1
                        },
                        new
                        {
                            Id = 26,
                            Code = "P026",
                            Name = "Product 26",
                            Note = "Description for product 26",
                            Price = 140.0m,
                            Quantity = 74,
                            catid = 2
                        },
                        new
                        {
                            Id = 27,
                            Code = "P027",
                            Name = "Product 27",
                            Note = "Description for product 27",
                            Price = 145.0m,
                            Quantity = 73,
                            catid = 3
                        },
                        new
                        {
                            Id = 28,
                            Code = "P028",
                            Name = "Product 28",
                            Note = "Description for product 28",
                            Price = 150.0m,
                            Quantity = 72,
                            catid = 4
                        },
                        new
                        {
                            Id = 29,
                            Code = "P029",
                            Name = "Product 29",
                            Note = "Description for product 29",
                            Price = 155.0m,
                            Quantity = 71,
                            catid = 5
                        },
                        new
                        {
                            Id = 30,
                            Code = "P030",
                            Name = "Product 30",
                            Note = "Description for product 30",
                            Price = 160.0m,
                            Quantity = 70,
                            catid = 1
                        },
                        new
                        {
                            Id = 31,
                            Code = "P031",
                            Name = "Product 31",
                            Note = "Description for product 31",
                            Price = 165.0m,
                            Quantity = 69,
                            catid = 2
                        },
                        new
                        {
                            Id = 32,
                            Code = "P032",
                            Name = "Product 32",
                            Note = "Description for product 32",
                            Price = 170.0m,
                            Quantity = 68,
                            catid = 3
                        },
                        new
                        {
                            Id = 33,
                            Code = "P033",
                            Name = "Product 33",
                            Note = "Description for product 33",
                            Price = 175.0m,
                            Quantity = 67,
                            catid = 4
                        },
                        new
                        {
                            Id = 34,
                            Code = "P034",
                            Name = "Product 34",
                            Note = "Description for product 34",
                            Price = 180.0m,
                            Quantity = 66,
                            catid = 5
                        },
                        new
                        {
                            Id = 35,
                            Code = "P035",
                            Name = "Product 35",
                            Note = "Description for product 35",
                            Price = 185.0m,
                            Quantity = 65,
                            catid = 1
                        },
                        new
                        {
                            Id = 36,
                            Code = "P036",
                            Name = "Product 36",
                            Note = "Description for product 36",
                            Price = 190.0m,
                            Quantity = 64,
                            catid = 2
                        },
                        new
                        {
                            Id = 37,
                            Code = "P037",
                            Name = "Product 37",
                            Note = "Description for product 37",
                            Price = 195.0m,
                            Quantity = 63,
                            catid = 3
                        },
                        new
                        {
                            Id = 38,
                            Code = "P038",
                            Name = "Product 38",
                            Note = "Description for product 38",
                            Price = 200.0m,
                            Quantity = 62,
                            catid = 4
                        },
                        new
                        {
                            Id = 39,
                            Code = "P039",
                            Name = "Product 39",
                            Note = "Description for product 39",
                            Price = 205.0m,
                            Quantity = 61,
                            catid = 5
                        },
                        new
                        {
                            Id = 40,
                            Code = "P040",
                            Name = "Product 40",
                            Note = "Description for product 40",
                            Price = 210.0m,
                            Quantity = 60,
                            catid = 1
                        },
                        new
                        {
                            Id = 41,
                            Code = "P041",
                            Name = "Product 41",
                            Note = "Description for product 41",
                            Price = 215.0m,
                            Quantity = 59,
                            catid = 2
                        },
                        new
                        {
                            Id = 42,
                            Code = "P042",
                            Name = "Product 42",
                            Note = "Description for product 42",
                            Price = 220.0m,
                            Quantity = 58,
                            catid = 3
                        },
                        new
                        {
                            Id = 43,
                            Code = "P043",
                            Name = "Product 43",
                            Note = "Description for product 43",
                            Price = 225.0m,
                            Quantity = 57,
                            catid = 4
                        },
                        new
                        {
                            Id = 44,
                            Code = "P044",
                            Name = "Product 44",
                            Note = "Description for product 44",
                            Price = 230.0m,
                            Quantity = 56,
                            catid = 5
                        },
                        new
                        {
                            Id = 45,
                            Code = "P045",
                            Name = "Product 45",
                            Note = "Description for product 45",
                            Price = 235.0m,
                            Quantity = 55,
                            catid = 1
                        },
                        new
                        {
                            Id = 46,
                            Code = "P046",
                            Name = "Product 46",
                            Note = "Description for product 46",
                            Price = 240.0m,
                            Quantity = 54,
                            catid = 2
                        },
                        new
                        {
                            Id = 47,
                            Code = "P047",
                            Name = "Product 47",
                            Note = "Description for product 47",
                            Price = 245.0m,
                            Quantity = 53,
                            catid = 3
                        },
                        new
                        {
                            Id = 48,
                            Code = "P048",
                            Name = "Product 48",
                            Note = "Description for product 48",
                            Price = 250.0m,
                            Quantity = 52,
                            catid = 4
                        },
                        new
                        {
                            Id = 49,
                            Code = "P049",
                            Name = "Product 49",
                            Note = "Description for product 49",
                            Price = 255.0m,
                            Quantity = 51,
                            catid = 5
                        },
                        new
                        {
                            Id = 50,
                            Code = "P050",
                            Name = "Product 50",
                            Note = "Description for product 50",
                            Price = 260.0m,
                            Quantity = 50,
                            catid = 1
                        },
                        new
                        {
                            Id = 51,
                            Code = "P051",
                            Name = "Product 51",
                            Note = "Description for product 51",
                            Price = 265.0m,
                            Quantity = 49,
                            catid = 2
                        },
                        new
                        {
                            Id = 52,
                            Code = "P052",
                            Name = "Product 52",
                            Note = "Description for product 52",
                            Price = 270.0m,
                            Quantity = 48,
                            catid = 3
                        },
                        new
                        {
                            Id = 53,
                            Code = "P053",
                            Name = "Product 53",
                            Note = "Description for product 53",
                            Price = 275.0m,
                            Quantity = 47,
                            catid = 4
                        },
                        new
                        {
                            Id = 54,
                            Code = "P054",
                            Name = "Product 54",
                            Note = "Description for product 54",
                            Price = 280.0m,
                            Quantity = 46,
                            catid = 5
                        },
                        new
                        {
                            Id = 55,
                            Code = "P055",
                            Name = "Product 55",
                            Note = "Description for product 55",
                            Price = 285.0m,
                            Quantity = 45,
                            catid = 1
                        },
                        new
                        {
                            Id = 56,
                            Code = "P056",
                            Name = "Product 56",
                            Note = "Description for product 56",
                            Price = 290.0m,
                            Quantity = 44,
                            catid = 2
                        },
                        new
                        {
                            Id = 57,
                            Code = "P057",
                            Name = "Product 57",
                            Note = "Description for product 57",
                            Price = 295.0m,
                            Quantity = 43,
                            catid = 3
                        },
                        new
                        {
                            Id = 58,
                            Code = "P058",
                            Name = "Product 58",
                            Note = "Description for product 58",
                            Price = 300.0m,
                            Quantity = 42,
                            catid = 4
                        },
                        new
                        {
                            Id = 59,
                            Code = "P059",
                            Name = "Product 59",
                            Note = "Description for product 59",
                            Price = 305.0m,
                            Quantity = 41,
                            catid = 5
                        },
                        new
                        {
                            Id = 60,
                            Code = "P060",
                            Name = "Product 60",
                            Note = "Description for product 60",
                            Price = 310.0m,
                            Quantity = 40,
                            catid = 1
                        },
                        new
                        {
                            Id = 61,
                            Code = "P061",
                            Name = "Product 61",
                            Note = "Description for product 61",
                            Price = 315.0m,
                            Quantity = 39,
                            catid = 2
                        },
                        new
                        {
                            Id = 62,
                            Code = "P062",
                            Name = "Product 62",
                            Note = "Description for product 62",
                            Price = 320.0m,
                            Quantity = 38,
                            catid = 3
                        },
                        new
                        {
                            Id = 63,
                            Code = "P063",
                            Name = "Product 63",
                            Note = "Description for product 63",
                            Price = 325.0m,
                            Quantity = 37,
                            catid = 4
                        },
                        new
                        {
                            Id = 64,
                            Code = "P064",
                            Name = "Product 64",
                            Note = "Description for product 64",
                            Price = 330.0m,
                            Quantity = 36,
                            catid = 5
                        },
                        new
                        {
                            Id = 65,
                            Code = "P065",
                            Name = "Product 65",
                            Note = "Description for product 65",
                            Price = 335.0m,
                            Quantity = 35,
                            catid = 1
                        },
                        new
                        {
                            Id = 66,
                            Code = "P066",
                            Name = "Product 66",
                            Note = "Description for product 66",
                            Price = 340.0m,
                            Quantity = 34,
                            catid = 2
                        },
                        new
                        {
                            Id = 67,
                            Code = "P067",
                            Name = "Product 67",
                            Note = "Description for product 67",
                            Price = 345.0m,
                            Quantity = 33,
                            catid = 3
                        },
                        new
                        {
                            Id = 68,
                            Code = "P068",
                            Name = "Product 68",
                            Note = "Description for product 68",
                            Price = 350.0m,
                            Quantity = 32,
                            catid = 4
                        },
                        new
                        {
                            Id = 69,
                            Code = "P069",
                            Name = "Product 69",
                            Note = "Description for product 69",
                            Price = 355.0m,
                            Quantity = 31,
                            catid = 5
                        },
                        new
                        {
                            Id = 70,
                            Code = "P070",
                            Name = "Product 70",
                            Note = "Description for product 70",
                            Price = 360.0m,
                            Quantity = 30,
                            catid = 1
                        },
                        new
                        {
                            Id = 71,
                            Code = "P071",
                            Name = "Product 71",
                            Note = "Description for product 71",
                            Price = 365.0m,
                            Quantity = 29,
                            catid = 2
                        },
                        new
                        {
                            Id = 72,
                            Code = "P072",
                            Name = "Product 72",
                            Note = "Description for product 72",
                            Price = 370.0m,
                            Quantity = 28,
                            catid = 3
                        },
                        new
                        {
                            Id = 73,
                            Code = "P073",
                            Name = "Product 73",
                            Note = "Description for product 73",
                            Price = 375.0m,
                            Quantity = 27,
                            catid = 4
                        },
                        new
                        {
                            Id = 74,
                            Code = "P074",
                            Name = "Product 74",
                            Note = "Description for product 74",
                            Price = 380.0m,
                            Quantity = 26,
                            catid = 5
                        },
                        new
                        {
                            Id = 75,
                            Code = "P075",
                            Name = "Product 75",
                            Note = "Description for product 75",
                            Price = 385.0m,
                            Quantity = 25,
                            catid = 1
                        },
                        new
                        {
                            Id = 76,
                            Code = "P076",
                            Name = "Product 76",
                            Note = "Description for product 76",
                            Price = 390.0m,
                            Quantity = 24,
                            catid = 2
                        },
                        new
                        {
                            Id = 77,
                            Code = "P077",
                            Name = "Product 77",
                            Note = "Description for product 77",
                            Price = 395.0m,
                            Quantity = 23,
                            catid = 3
                        },
                        new
                        {
                            Id = 78,
                            Code = "P078",
                            Name = "Product 78",
                            Note = "Description for product 78",
                            Price = 400.0m,
                            Quantity = 22,
                            catid = 4
                        },
                        new
                        {
                            Id = 79,
                            Code = "P079",
                            Name = "Product 79",
                            Note = "Description for product 79",
                            Price = 405.0m,
                            Quantity = 21,
                            catid = 5
                        },
                        new
                        {
                            Id = 80,
                            Code = "P080",
                            Name = "Product 80",
                            Note = "Description for product 80",
                            Price = 410.0m,
                            Quantity = 20,
                            catid = 1
                        },
                        new
                        {
                            Id = 81,
                            Code = "P081",
                            Name = "Product 81",
                            Note = "Description for product 81",
                            Price = 415.0m,
                            Quantity = 19,
                            catid = 2
                        },
                        new
                        {
                            Id = 82,
                            Code = "P082",
                            Name = "Product 82",
                            Note = "Description for product 82",
                            Price = 420.0m,
                            Quantity = 18,
                            catid = 3
                        },
                        new
                        {
                            Id = 83,
                            Code = "P083",
                            Name = "Product 83",
                            Note = "Description for product 83",
                            Price = 425.0m,
                            Quantity = 17,
                            catid = 4
                        },
                        new
                        {
                            Id = 84,
                            Code = "P084",
                            Name = "Product 84",
                            Note = "Description for product 84",
                            Price = 430.0m,
                            Quantity = 16,
                            catid = 5
                        },
                        new
                        {
                            Id = 85,
                            Code = "P085",
                            Name = "Product 85",
                            Note = "Description for product 85",
                            Price = 435.0m,
                            Quantity = 15,
                            catid = 1
                        },
                        new
                        {
                            Id = 86,
                            Code = "P086",
                            Name = "Product 86",
                            Note = "Description for product 86",
                            Price = 440.0m,
                            Quantity = 14,
                            catid = 2
                        },
                        new
                        {
                            Id = 87,
                            Code = "P087",
                            Name = "Product 87",
                            Note = "Description for product 87",
                            Price = 445.0m,
                            Quantity = 13,
                            catid = 3
                        },
                        new
                        {
                            Id = 88,
                            Code = "P088",
                            Name = "Product 88",
                            Note = "Description for product 88",
                            Price = 450.0m,
                            Quantity = 12,
                            catid = 4
                        },
                        new
                        {
                            Id = 89,
                            Code = "P089",
                            Name = "Product 89",
                            Note = "Description for product 89",
                            Price = 455.0m,
                            Quantity = 11,
                            catid = 5
                        },
                        new
                        {
                            Id = 90,
                            Code = "P090",
                            Name = "Product 90",
                            Note = "Description for product 90",
                            Price = 460.0m,
                            Quantity = 10,
                            catid = 1
                        },
                        new
                        {
                            Id = 91,
                            Code = "P091",
                            Name = "Product 91",
                            Note = "Description for product 91",
                            Price = 465.0m,
                            Quantity = 9,
                            catid = 2
                        },
                        new
                        {
                            Id = 92,
                            Code = "P092",
                            Name = "Product 92",
                            Note = "Description for product 92",
                            Price = 470.0m,
                            Quantity = 8,
                            catid = 3
                        },
                        new
                        {
                            Id = 93,
                            Code = "P093",
                            Name = "Product 93",
                            Note = "Description for product 93",
                            Price = 475.0m,
                            Quantity = 7,
                            catid = 4
                        },
                        new
                        {
                            Id = 94,
                            Code = "P094",
                            Name = "Product 94",
                            Note = "Description for product 94",
                            Price = 480.0m,
                            Quantity = 6,
                            catid = 5
                        },
                        new
                        {
                            Id = 95,
                            Code = "P095",
                            Name = "Product 95",
                            Note = "Description for product 95",
                            Price = 485.0m,
                            Quantity = 5,
                            catid = 1
                        },
                        new
                        {
                            Id = 96,
                            Code = "P096",
                            Name = "Product 96",
                            Note = "Description for product 96",
                            Price = 490.0m,
                            Quantity = 4,
                            catid = 2
                        },
                        new
                        {
                            Id = 97,
                            Code = "P097",
                            Name = "Product 97",
                            Note = "Description for product 97",
                            Price = 495.0m,
                            Quantity = 3,
                            catid = 3
                        },
                        new
                        {
                            Id = 98,
                            Code = "P098",
                            Name = "Product 98",
                            Note = "Description for product 98",
                            Price = 500.0m,
                            Quantity = 2,
                            catid = 4
                        },
                        new
                        {
                            Id = 99,
                            Code = "P099",
                            Name = "Product 99",
                            Note = "Description for product 99",
                            Price = 505.0m,
                            Quantity = 1,
                            catid = 5
                        },
                        new
                        {
                            Id = 100,
                            Code = "P100",
                            Name = "Product 100",
                            Note = "Description for product 100",
                            Price = 510.0m,
                            Quantity = 0,
                            catid = 1
                        });
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.InvoiceDetail", b =>
                {
                    b.HasOne("ProjectEntity_Dapper.Models.Invoicess", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectEntity_Dapper.Models.Product", "product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Invoicess", b =>
                {
                    b.HasOne("ProjectEntity_Dapper.Models.Customers", "Customer")
                        .WithMany("invoice")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Product", b =>
                {
                    b.HasOne("ProjectEntity_Dapper.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("catid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Customers", b =>
                {
                    b.Navigation("invoice");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Invoicess", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("ProjectEntity_Dapper.Models.Product", b =>
                {
                    b.Navigation("InvoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
