namespace ProjectEntity_Dapper.Invoice
{
    partial class frm_add_Invoice
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_add_Invoice));
            label2 = new Label();
            pictureBox2 = new PictureBox();
            AutoGeneratedId = new Label();
            txt_note = new TextBox();
            label1 = new Label();
            dtpInvoiceDate = new DateTimePicker();
            comboBoxCustomers = new ComboBox();
            label3 = new Label();
            txt_phone = new TextBox();
            label4 = new Label();
            label5 = new Label();
            label6 = new Label();
            dgv_invoiceDetails = new DataGridView();
            lblTotalAmount = new Label();
            btn_back = new Button();
            btn_Create = new Button();
            lbl_IDGenerator = new Label();
            label7 = new Label();
            comboBoxProducts = new ComboBox();
            btn_addProduct = new Button();
            numUDQuantity = new NumericUpDown();
            label8 = new Label();
            btn_addCustomer = new Button();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgv_invoiceDetails).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numUDQuantity).BeginInit();
            SuspendLayout();
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.ForeColor = Color.White;
            label2.Location = new Point(12, 14);
            label2.Name = "label2";
            label2.Size = new Size(142, 32);
            label2.TabIndex = 39;
            label2.Text = "Add Invoice";
            // 
            // pictureBox2
            // 
            pictureBox2.Image = Properties.Resources.icons8_close_48;
            pictureBox2.Location = new Point(799, 9);
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Size = new Size(37, 37);
            pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox2.TabIndex = 38;
            pictureBox2.TabStop = false;
            pictureBox2.Click += pictureBox2_Click;
            // 
            // AutoGeneratedId
            // 
            AutoGeneratedId.AutoSize = true;
            AutoGeneratedId.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            AutoGeneratedId.ForeColor = Color.White;
            AutoGeneratedId.Location = new Point(27, 77);
            AutoGeneratedId.Name = "AutoGeneratedId";
            AutoGeneratedId.Size = new Size(127, 21);
            AutoGeneratedId.TabIndex = 41;
            AutoGeneratedId.Text = "Number Invoice";
            // 
            // txt_note
            // 
            txt_note.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txt_note.Location = new Point(560, 196);
            txt_note.MaximumSize = new Size(240, 50);
            txt_note.MinimumSize = new Size(240, 35);
            txt_note.Name = "txt_note";
            txt_note.PlaceholderText = "Write Name Here......";
            txt_note.Size = new Size(240, 35);
            txt_note.TabIndex = 6;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.White;
            label1.Location = new Point(483, 74);
            label1.Name = "label1";
            label1.Size = new Size(44, 21);
            label1.TabIndex = 43;
            label1.Text = "Date";
            // 
            // dtpInvoiceDate
            // 
            dtpInvoiceDate.Font = new Font("Segoe UI", 12F);
            dtpInvoiceDate.Location = new Point(560, 71);
            dtpInvoiceDate.Name = "dtpInvoiceDate";
            dtpInvoiceDate.Size = new Size(240, 29);
            dtpInvoiceDate.TabIndex = 4;
            // 
            // comboBoxCustomers
            // 
            comboBoxCustomers.Font = new Font("Segoe UI", 12F);
            comboBoxCustomers.FormattingEnabled = true;
            comboBoxCustomers.Location = new Point(169, 135);
            comboBoxCustomers.Name = "comboBoxCustomers";
            comboBoxCustomers.Size = new Size(240, 29);
            comboBoxCustomers.TabIndex = 1;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.ForeColor = Color.White;
            label3.Location = new Point(27, 135);
            label3.Name = "label3";
            label3.Size = new Size(81, 21);
            label3.TabIndex = 46;
            label3.Text = "Customer";
            // 
            // txt_phone
            // 
            txt_phone.Font = new Font("Segoe UI", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txt_phone.Location = new Point(560, 135);
            txt_phone.MaximumSize = new Size(240, 50);
            txt_phone.MinimumSize = new Size(240, 35);
            txt_phone.Name = "txt_phone";
            txt_phone.PlaceholderText = "Enter Number Phone Here......";
            txt_phone.Size = new Size(240, 35);
            txt_phone.TabIndex = 5;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label4.ForeColor = Color.White;
            label4.Location = new Point(483, 143);
            label4.Name = "label4";
            label4.Size = new Size(56, 21);
            label4.TabIndex = 48;
            label4.Text = "Phone";
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label5.ForeColor = Color.White;
            label5.Location = new Point(483, 199);
            label5.Name = "label5";
            label5.Size = new Size(47, 21);
            label5.TabIndex = 49;
            label5.Text = "Note";
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label6.ForeColor = Color.White;
            label6.Location = new Point(367, 298);
            label6.Name = "label6";
            label6.Size = new Size(172, 32);
            label6.TabIndex = 50;
            label6.Text = "Invoice Details";
            // 
            // dgv_invoiceDetails
            // 
            dgv_invoiceDetails.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgv_invoiceDetails.Location = new Point(110, 333);
            dgv_invoiceDetails.Name = "dgv_invoiceDetails";
            dgv_invoiceDetails.Size = new Size(659, 236);
            dgv_invoiceDetails.TabIndex = 51;
            dgv_invoiceDetails.CellContentClick += dgv_invoiceDetails_CellContentClick;
            // 
            // lblTotalAmount
            // 
            lblTotalAmount.AutoSize = true;
            lblTotalAmount.Font = new Font("Segoe UI Semibold", 18F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblTotalAmount.ForeColor = Color.White;
            lblTotalAmount.Location = new Point(116, 600);
            lblTotalAmount.Name = "lblTotalAmount";
            lblTotalAmount.Size = new Size(0, 32);
            lblTotalAmount.TabIndex = 53;
            // 
            // btn_back
            // 
            btn_back.BackColor = Color.FromArgb(64, 64, 64);
            btn_back.Cursor = Cursors.Hand;
            btn_back.FlatAppearance.BorderSize = 0;
            btn_back.FlatStyle = FlatStyle.Flat;
            btn_back.Font = new Font("Segoe UI Semibold", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btn_back.ForeColor = SystemColors.ButtonFace;
            btn_back.Image = Properties.Resources.icons8_back_50;
            btn_back.ImageAlign = ContentAlignment.MiddleLeft;
            btn_back.Location = new Point(12, 591);
            btn_back.Name = "btn_back";
            btn_back.Size = new Size(165, 54);
            btn_back.TabIndex = 8;
            btn_back.Text = "Back";
            btn_back.TextAlign = ContentAlignment.MiddleRight;
            btn_back.UseVisualStyleBackColor = false;
            btn_back.Click += btn_back_Click;
            // 
            // btn_Create
            // 
            btn_Create.BackColor = Color.FromArgb(0, 64, 64);
            btn_Create.Cursor = Cursors.Hand;
            btn_Create.FlatAppearance.BorderSize = 0;
            btn_Create.FlatStyle = FlatStyle.Flat;
            btn_Create.Font = new Font("Segoe UI Semibold", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btn_Create.ForeColor = SystemColors.ButtonFace;
            btn_Create.Image = Properties.Resources.icons8_add_48;
            btn_Create.ImageAlign = ContentAlignment.MiddleRight;
            btn_Create.Location = new Point(659, 591);
            btn_Create.Name = "btn_Create";
            btn_Create.Size = new Size(165, 54);
            btn_Create.TabIndex = 7;
            btn_Create.Text = "Add";
            btn_Create.TextAlign = ContentAlignment.MiddleLeft;
            btn_Create.UseVisualStyleBackColor = false;
            btn_Create.Click += btn_Create_Click;
            // 
            // lbl_IDGenerator
            // 
            lbl_IDGenerator.AutoSize = true;
            lbl_IDGenerator.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lbl_IDGenerator.ForeColor = Color.White;
            lbl_IDGenerator.Location = new Point(169, 79);
            lbl_IDGenerator.Name = "lbl_IDGenerator";
            lbl_IDGenerator.Size = new Size(0, 21);
            lbl_IDGenerator.TabIndex = 56;
            // 
            // label7
            // 
            label7.AutoSize = true;
            label7.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label7.ForeColor = Color.White;
            label7.Location = new Point(27, 191);
            label7.Name = "label7";
            label7.Size = new Size(68, 21);
            label7.TabIndex = 58;
            label7.Text = "Product";
            // 
            // comboBoxProducts
            // 
            comboBoxProducts.Font = new Font("Segoe UI", 12F);
            comboBoxProducts.FormattingEnabled = true;
            comboBoxProducts.Location = new Point(169, 191);
            comboBoxProducts.Name = "comboBoxProducts";
            comboBoxProducts.Size = new Size(240, 29);
            comboBoxProducts.TabIndex = 2;
            // 
            // btn_addProduct
            // 
            btn_addProduct.BackColor = Color.Transparent;
            btn_addProduct.BackgroundImage = Properties.Resources.icons8_add_48;
            btn_addProduct.BackgroundImageLayout = ImageLayout.Stretch;
            btn_addProduct.Cursor = Cursors.Hand;
            btn_addProduct.FlatAppearance.BorderSize = 0;
            btn_addProduct.FlatStyle = FlatStyle.Flat;
            btn_addProduct.Font = new Font("Segoe UI Semibold", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btn_addProduct.ForeColor = SystemColors.ButtonFace;
            btn_addProduct.Location = new Point(416, 237);
            btn_addProduct.Name = "btn_addProduct";
            btn_addProduct.Size = new Size(43, 35);
            btn_addProduct.TabIndex = 59;
            btn_addProduct.TextAlign = ContentAlignment.MiddleLeft;
            btn_addProduct.UseVisualStyleBackColor = false;
            btn_addProduct.Click += btn_addProduct_Click;
            // 
            // numUDQuantity
            // 
            numUDQuantity.Font = new Font("Segoe UI", 12F);
            numUDQuantity.Location = new Point(169, 239);
            numUDQuantity.Name = "numUDQuantity";
            numUDQuantity.Size = new Size(240, 29);
            numUDQuantity.TabIndex = 3;
            // 
            // label8
            // 
            label8.AutoSize = true;
            label8.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label8.ForeColor = Color.White;
            label8.Location = new Point(27, 241);
            label8.Name = "label8";
            label8.Size = new Size(72, 21);
            label8.TabIndex = 61;
            label8.Text = "Quantity";
            // 
            // btn_addCustomer
            // 
            btn_addCustomer.BackColor = Color.Transparent;
            btn_addCustomer.BackgroundImage = Properties.Resources.icons8_add_48;
            btn_addCustomer.BackgroundImageLayout = ImageLayout.Stretch;
            btn_addCustomer.Cursor = Cursors.Hand;
            btn_addCustomer.FlatAppearance.BorderSize = 0;
            btn_addCustomer.FlatStyle = FlatStyle.Flat;
            btn_addCustomer.Font = new Font("Segoe UI Semibold", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btn_addCustomer.ForeColor = SystemColors.ButtonFace;
            btn_addCustomer.Location = new Point(415, 130);
            btn_addCustomer.Name = "btn_addCustomer";
            btn_addCustomer.Size = new Size(43, 35);
            btn_addCustomer.TabIndex = 62;
            btn_addCustomer.TextAlign = ContentAlignment.MiddleLeft;
            btn_addCustomer.UseVisualStyleBackColor = false;
            btn_addCustomer.Click += btn_addCustomer_Click;
            // 
            // frm_add_Invoice
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.Teal;
            ClientSize = new Size(848, 657);
            Controls.Add(btn_addCustomer);
            Controls.Add(label8);
            Controls.Add(numUDQuantity);
            Controls.Add(btn_addProduct);
            Controls.Add(label7);
            Controls.Add(comboBoxProducts);
            Controls.Add(lbl_IDGenerator);
            Controls.Add(btn_back);
            Controls.Add(btn_Create);
            Controls.Add(lblTotalAmount);
            Controls.Add(dgv_invoiceDetails);
            Controls.Add(label6);
            Controls.Add(label5);
            Controls.Add(label4);
            Controls.Add(txt_phone);
            Controls.Add(label3);
            Controls.Add(comboBoxCustomers);
            Controls.Add(dtpInvoiceDate);
            Controls.Add(txt_note);
            Controls.Add(label1);
            Controls.Add(AutoGeneratedId);
            Controls.Add(label2);
            Controls.Add(pictureBox2);
            FormBorderStyle = FormBorderStyle.None;
            Icon = (Icon)resources.GetObject("$this.Icon");
            Name = "frm_add_Invoice";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "add_Invoice";
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgv_invoiceDetails).EndInit();
            ((System.ComponentModel.ISupportInitialize)numUDQuantity).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private Label label2;
        private PictureBox pictureBox2;
        private Label AutoGeneratedId;
        private TextBox txt_note;
        private Label label1;
        private DateTimePicker dtpInvoiceDate;
        private ComboBox comboBoxCustomers;
        private Label label3;
        private TextBox txt_phone;
        private Label label4;
        private Label label5;
        private Label label6;
        private DataGridView dgv_invoiceDetails;
        private Label lblTotalAmount;
        private Button btn_back;
        private Button btn_Create;
        private Label lbl_IDGenerator;
        private Label label7;
        private ComboBox comboBoxProducts;
        private Button btn_addProduct;
        private NumericUpDown numUDQuantity;
        private Label label8;
        private Button btn_addCustomer;
    }
}